---

collections:
  - name: http://gitea.k8scluster.net/smys/kubernetes.core.git
    type: git
    version: 5.0.0
  - name: http://gitea.k8scluster.net/smys/community.docker.git
    type: git
    version: 3.13.1
  - name: http://gitea.k8scluster.net/smys/community.library_inventory_filtering.git
    type: git
    version: 1.0.1