---

- name: Render Tigera Calico manifest from template
  ansible.builtin.template:
    src: tigera-operator.yaml.j2
    dest: /tmp/tigera-operator.yaml

- name: Render Calico manifest from template
  ansible.builtin.template:
    src: calico-custom-resources.yaml.j2
    dest: /tmp/calico-custom-resources.yaml

- name: Install the Tigera Calico operator and custom resource definitions
  ansible.builtin.shell: kubectl create -f /tmp/tigera-operator.yaml

- name: Apply Calico manifest
  ansible.builtin.shell: kubectl apply -f /tmp/calico-custom-resources.yaml
