---

- name: Remove old Docker instances
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Setup Docker Repository
  ansible.builtin.template:
      src: kubeadm-init.yml.j2
      dest: /root/kubeadm-init.yml

- name: Setup Docker Repository
  ansible.builtin.dnf:
    name: yum-utils
    state: present