---

- block:
    - name: Install containerd.io
      ansible.builtin.package: 
        name: containerd.io
        state: present
        update_cache: yes 

    - name: Create containerd directory
      ansible.builtin.file: 
        name: /etc/containerd
        state: directory
    
    - name: Check if config.toml is updated
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^#[grpc]'
        state: absent
      check_mode: yes
      changed_when: false
      register: containerd_config

    - name: Render containerd default config
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      when: 
        - containerd_config.found

    - name: enable SystemdCgroup for containerd
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup(.*)$'
        replace: '\1SystemdCgroup = true'
      notify:
        - reload containerd
    
    - name: start and enable containerd
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: yes
        
  when: kubernetes_cri == 'containerd'

- name: Force all notified handlers to run now
  meta: flush_handlers