---

- name: Remove old Docker instances
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Install Containerd Engine
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Generate containerd default config
  ansible.builtin.shell: |
    containerd config default > /etc/containerd/config.toml

- name: Configure the systemd cgroup driver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '(SystemdCgroup = )false'
    replace: '\1true'
    backup: yes   

- name: Update pause sandbox_image version
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(.*sandbox_image\s*=\s*)(.*)$'
    replace: '\1"{{ kubernetes_pause_image }}"'
    backup: yes

- name: Enable insecure Docker local registry
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: restarted

- name: Ensure Containerd is started and enabled
  ansible.builtin.systemd_service:
    name: containerd
    enabled: true
    state: restarted

