---

- name: Remove old Docker instances
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Setup Docker Repository
  ansible.builtin.template:
      src: docker-ce.repo.j2
      dest: /etc/yum.repos.d/docker-ce.repo
      owner: root
      group: root
      mode: '0644'

#- name: Add Docker GPG key
#  ansible.builtin.rpm_key:
#    key: https://download.docker.com/linux/centos/gpg
#    state: present

- name: Install Containerd Engine
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd_service:
    name: docker
    enabled: yes
    state: restarted

- name: Generate containerd default config
  ansible.builtin.shell: |
    containerd config default > /etc/containerd/config.toml

- name: Configure the systemd cgroup driver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '(SystemdCgroup = )false'
    replace: '\1true'
    backup: yes   

- name: Update pause sandbox_image version
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^\s*(sandbox_image\s*=\s*\"registry\.k8s\.io\/).*'
    replace: '\1"{{ pause_image }}"'
    backup: yes

- name: Ensure Containerd is started and enabled
  ansible.builtin.systemd_service:
    name: containerd
    enabled: yes
    state: restarted
