---

- include_tasks: 
    file: preflight.yaml
    apply:
      tags: preflight
  tags:
    - preflight
    - all

- include_tasks: 
    file: install-ce.yaml
    apply:
      tags: install-ce
  tags: 
    - install-ce
    - all