---

- name: Pre-flight configuration for all nodes
  import_tasks: preflight.yaml
  tags:
    - preflight
    - all

- name: Install Container Engine on all nodes
  import_tasks: install-ce.yaml
  tags: 
    - install-ce
    - all

- name: Install Kubectl on all nodes
  import_tasks: install-kubectl.yaml
  tags: 
    - kubectl
    - all

- name: Initialize K8s cluster on control plane node(s) 
  import_tasks: init-cluster.yaml
  tags: 
    - kubeinit
    - all

- name: Join worker nodes to the K8s cluster
  import_tasks: join-cluster.yaml
  tags: 
    - kubejoin
    - all
