---

- include_tasks: 
    file: preflight.yaml
    apply:
      tags: preflight
  tags:
    - preflight
    - all

- include_tasks: 
    file: install-ce.yaml
    apply:
      tags: install-ce
  tags: 
    - install-ce
    - all

- include_tasks: 
    file: install-kubectl.yaml
    apply:
      tags: kubectl
  tags: 
    - kubectl
    - all

- include_tasks: 
    file: init-cluster.yaml
    apply:
      tags: kubeinit
  tags: 
    - kubeinit
    - all

- include_tasks: 
    file: join-cluster.yaml
    apply:
      tags: kubejoin
  tags: 
    - kubejoin
    - all
