---

- name: Install updates
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Reboot
  ansible.builtin.reboot:

- name: Disable SWAP
  ansible.builtin.shell: swapoff -a

- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
    backup: yes

- name: Disable firewalld
  ansible.builtin.systemd:
    name: firewalld 
    state: stopped 
    enabled: no
    
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Enable IPv4 packet forwarding
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    block: net.ipv4.ip_forward = 1

- name: Apply sysctl params without reboot
  ansible.builtin.command: sysctl --system