---

- name: Install updates
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  register: dnf_update_result

- name: Reboot
  ansible.builtin.reboot:
  when: dnf_update_result.changed

- name: Disable SWAP
  ansible.builtin.shell: swapoff -a

- name: Disable SWAP in fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.+swap.*)$'
    replace: '# \1'
    backup: yes

- name: Disable firewalld
  ansible.builtin.systemd_service:
    name: firewalld 
    state: stopped 
    enabled: false
  when: disable_firewall
    
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Enable IPv4 packet forwarding
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    block: net.ipv4.ip_forward = 1
  register: packet_forwarding_result

- name: Apply sysctl params without reboot
  ansible.builtin.command: sysctl --system
  when: packet_forwarding_result.changed

- name: Setup cluster hostnames in hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    create: yes
    state: present
  loop: "{{ groups['all'] }}"

- name: Add Docker Registry DNS in hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ docker_registry_ip }} {{ docker_registry_hostname }}"
    create: yes
    state: present

- name: Import Docker Registry CA SSL Certificate
  ansible.builtin.template:
    src: harbor-ca.crt.j2
    dest: /etc/pki/ca-trust/source/anchors/harbor-ca.crt
    owner: root
    group: root
    mode: '0644'

- name: Update CA trust after importing CA cert
  ansible.builtin.shell: update-ca-trust

